########################################
#                                      #
#            HOME ASSISTANT            #
#                                      #
########################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 46
  unit_system: metric
  time_zone: Australia/Sydney
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config

########################################
#                                      #
#              COMPONENTS              #
#                                      #
########################################

#https://www.home-assistant.io/integrations/default_config/
default_config:

#https://www.home-assistant.io/components/downloader
downloader:
  download_dir: downloads

#https://www.home-assistant.io/integrations/dyson/
dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: AU

#https://www.home-assistant.io/components/frontend/
frontend:
  themes: !include_dir_merge_named themes

#https://www.home-assistant.io/components/nsw_rural_fire_service_feed/
geo_location:
  - platform: nsw_rural_fire_service_feed

#https://home-assistant.io/components/http/
http:
  ip_ban_enabled: true
  login_attempts_threshold: 10

#https://www.home-assistant.io/components/hue/
hue:
  bridges:
    - host: 192.168.1.103
      allow_unreachable: true
      allow_hue_groups: false

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml

#https://www.home-assistant.io/integrations/light.group
light:
  - platform: group
    name: Living Room Lights
    entities:
      - light.living_room_1
      - light.living_room_2
      - light.front_room_1
      - light.front_room_2
  - platform: group
    name: Back Room Lights
    entities:
      - light.living_room_1
      - light.living_room_2
  - platform: group
    name: Front Room Lights
    entities:
      - light.front_room_1
      - light.front_room_2

#https://github.com/fondberg/spotcast
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

#https://www.home-assistant.io/components/tts/
tts:
  - platform: google_translate

#https://www.home-assistant.io/components/vacuum.xiaomi_miio/
vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.21
    token: !secret xiaomi_miio

#https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

########################################
#                                      #
#          CUSTOM COMPONENTS           #
#                                      #
########################################

#https://custom-components.github.io/hacs/
hacs:
  token: !secret github_token
  sidepanel_title: HACS
  sidepanel_icon: mdi:store

########################################
#                                      #
#         CONFIGURATION FILES          #
#                                      #
########################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automations/
binary_sensor: !include binary_sensor.yaml
camera: !include cameras.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
notify: !include notification.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
switch: !include switches.yaml
zone: !include zones.yaml

########################################
#                                      #
#      END OF CONFIGURATION FILE       #
#                                      #
########################################
