########################################
#                                      #
#              RESOURCES               #
#                                      #
########################################

resources:
 - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
   type: module
 - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
   type: js
 - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
   type: module
 - url: /hacsfiles/button-card/button-card.js
   type: module
 - url: /local/simple-weather-card-bundle.js?v=0.7.2
   type: js

title: Home
views:
  - !include lovelace/rooms.yaml
  - !include lovelace/devicestatus.yaml
  - !include lovelace/home_climate.yaml
  - !include lovelace/security.yaml
  - !include lovelace/ha.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/switches.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/cameras.yaml
  - !include lovelace/statsndata.yaml

########################################
#                                      #
#      END OF CONFIGURATION FILE       #
#                                      #
########################################
