#https://www.home-assistant.io/docs/automation/

########################################
#                                      #
#     START OF CONFIGURATION FILE      #
#                                      #
########################################

- alias: 'Turn off Bedroom Aircon'
  initial_state: 'true'
  trigger:
      platform: time
      at: '02:00:00'
  action:
  - service: switch.turn_off
    entity_id: switch.aircon2
  - service: notify.james
    data_template:
      message: "Bedroom Aircon has been switched off."

########################################
#                                      #
#      END OF CONFIGURATION FILE       #
#                                      #
########################################
