#https://www.home-assistant.io/docs/automation/

########################################
#                                      #
#     START OF CONFIGURATION FILE      #
#                                      #
########################################

- alias: 'Garage Motion'
  initial_state: 'true'
  trigger:
      platform: state
      entity_id: binary_sensor.garage_sensor_motion
      from: 'off'
      to: 'on'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.generic_camera
      filename: /config/www/tmp/garage.jpg
  - service: notify.james
    data_template:
      data:
        attachment: /config/www/tmp/garage.jpg
        priority: 0
        sound: spacealarm
        url: homeassistant://
      message: "Motion at {{ now().strftime('%-I:%M:%S %p %-m/%-d/%y') }}"
      title: "Garage Motion"

########################################
#                                      #
#      END OF CONFIGURATION FILE       #
#                                      #
########################################
