#https://www.home-assistant.io/docs/automation/

########################################
#                                      #
#     START OF CONFIGURATION FILE      #
#                                      #
########################################

- alias: '22:00 - Lights Off'
  initial_state: 'true'
  trigger:
    platform: time
    at: "22:00:00"
  action:
    service: light.turn_off
    entity_id: light.living_room_lights
    data:
      transition: 900

- alias: 'Midnight - Lights Off'
  initial_state: 'true'
  trigger:
    platform: time
    at: "23:45:00"
  action:
    service: light.turn_off
    entity_id: light.living_room_lights
    data:
      transition: 900

- alias: 'Sunset Lights On'
  initial_state: 'true'
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
  - service: script.main_lights_on

########################################
#                                      #
#      END OF CONFIGURATION FILE       #
#                                      #
########################################
