#https://www.home-assistant.io/docs/automation/

########################################
#                                      #
#     START OF CONFIGURATION FILE      #
#                                      #
########################################

- alias: 'Home - Lights on'
  initial_state: 'true'
  trigger:
    platform: zone
    entity_id: device_tracker.james_phone, device_tracker.sarah_phone
    zone: zone.home
    event: enter
  action:
    service: light.turn_on
    entity_id: group.main_lights
  condition:
    condition: time
    after: '22:00:00'
    before: '23:59:00'

- alias: 'Sarah Home'
  trigger:
    - platform: zone
      entity_id: device_tracker.sarah_phone
      zone: zone.home
      event: enter
  action:
  - service: notify.james
    data_template:
      message: "Sarah has arrived home"
  - delay: '00:05:00'
  - service: tts.google_translate_say
    entity_id: media_player.kitchen
    data:
      message: 'Welcome home Sarah'
  - delay: '00:00:05'
  - service: media_player.play_media
    data:
      entity_id: media_player.kitchen
      media_content_id: !secret sound_sarah_arrival
      media_content_type: audio/mp3

- alias: 'James Home'
  initial_state: 'true'
  trigger:
    platform: zone
    entity_id: device_tracker.james_phone
    zone: zone.home
    event: enter
  action:
  - service: notify.sarah
    data_template:
      message: 'James has arrived home'
  - delay: '00:05:00'
  - service: tts.google_translate_say
    entity_id: media_player.kitchen
    data:
      message: 'Welcome home James'

########################################
#                                      #
#      END OF CONFIGURATION FILE       #
#                                      #
########################################
