#https://www.home-assistant.io/docs/automation/

########################################
#                                      #
#     START OF CONFIGURATION FILE      #
#                                      #
########################################

- alias: 'Update OpenUV'
  trigger:
      platform: time_pattern
      minutes: '/30'
  condition:
    condition: and
    conditions:
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
  action:
   service: openuv.update_data

########################################
#                                      #
#      END OF CONFIGURATION FILE       #
#                                      #
########################################
