#https://www.home-assistant.io/docs/automation/

########################################
#                                      #
#     START OF CONFIGURATION FILE      #
#                                      #
########################################

# When power is detected, and the washing machine is not in
# the Running state, change the status of the washing machine
# to Running.
# The status check will ensure we don't try to put the state
# to Running each time the power level changes, and we're already
# in the Running state.

- alias: Set washing machine active when power detected
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_watts
      above: 10
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Idle
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Clean
      - condition: state
        entity_id: sensor.washing_machine_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Running

# When the power drops, move the state of the washing machine to
# Finishing.

- alias: Set washing machine finished when power drops
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_watts
      below: 3
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Finishing

# Wait 5 minutes for us to be in the Finishing state before we
# decide the washing machine has finished. This way, if the
# washing machine is in between cycles and the power drops, we
# won't mark the washing machine cycle as finished too early.

- alias: Set washing machine clean after timeout
  trigger:
    - platform: state
      entity_id: input_select.washing_machine_status
      to: Finishing
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Clean

- alias: Send alert when washing machine is clean
  trigger:
    - platform: state
      entity_id: input_select.washing_machine_status
      to: Clean
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Clean
  action:
    - service: notify.james
      data:
        message: 'The washing machine has finished and is ready to be emptied!'
        title: 'Washing Machine Update'

########################################
#                                      #
#      END OF CONFIGURATION FILE       #
#                                      #
########################################
